### ISSUE TITLE
Add examples for the external dependencies

### ISSUE THREAD

**Issue by libratiger** [bazelbuild/examples#106]
There is no examples about the [external dependencies](https://docs.bazel.build/versions/0.28.0/external.html), it would be better for tutorial.

**Comment by aehlig** [comment]
> There is no examples about the [external dependencies](https://docs.bazel.build/versions/0.28.0/external.html), it would be better for tutorial.

The quoted page shows a couple of examples on how external dependencies can be used; could you please clarify what kind of examples you are missing.

**Comment by aehlig** [comment]
Also, if it is about _this_ repository, the [`WORKSPACE` file of the `tutorial` subdirectory](https://github.com/bazelbuild/examples/blob/8da4b9b4719685d89b840543c74ad5e399b3bcfa/tutorial/WORKSPACE) already uses quite a lot of external repositories; so real-world examples are included here as well.
