### ISSUE TITLE
Why adding a line of load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library") ?

### ISSUE THREAD

**Issue by wuhy08** [bazelbuild/examples#128]
I am new to Bazel and I am going thru the tutorial.

I see that almost all BUILD files added a line of `load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")`. I wonder what is the reason?

Build will fail with this line added but succeed without this line. Bazel version # is 0.26.0.

It seems to me that the BUILD file will explicitly load the `rule_cc`, is this required by newer version of Bazel?

**Comment by hlopko** [comment]
Yup this is because of incoming incompatible change https://github.com/bazelbuild/bazel/issues/8743.

Right now Bazel works both ways so people can forward-migrate. Eventually when the flag is flipped load statements will be required.

**Comment by nettyxiong** [comment]
mark
