### ISSUE TITLE
Cannot build end-to-end example with Bazel 2.0.0

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/examples#144]
At 84f298060b00f37924495ba4d8cbde1ff6d8e969 with Bazel 2.0.0 on Linux, I cannot `bazel build --nobuild //backend` (in `tutorial/`).

Log:
https://buildkite.com/bazel/bazel-bazel-examples/builds/311#481754ba-b78b-43b2-abef-f0865ce85b29

Local repro:
```
INFO: Repository 'remote_java_tools_linux' used the following cache hits instead of downloading the corresponding file.
 * Hash '3ff465e82954a70f49982610dd63f6f651beaa83c707dd637870b0e41cdcd2f0' for https://mirror.bazel.build/bazel_java_tools/releases/javac11/v7.0/java_tools_javac11_linux-v7.0.zip
If the definition of 'remote_java_tools_linux' was updated, verify that the hashes were also updated.
ERROR: /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/1fc5adba4fa8a524b4199134e1d30997/external/io_bazel_rules_appengine/appengine/BUILD:2:1: @io_bazel_rules_appengine//appengine:javax.servlet.api depends on @javax_servlet_api//jar:jar in repository @javax_servlet_api which failed to fetch. no such package '@javax_servlet_api//jar': java.io.IOException: Error downloading [http://central.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar] to /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/1fc5adba4fa8a524b4199134e1d30997/external/javax_servlet_api/javax.servlet-api-3.1.0.jar: GET returned 501 HTTPS Required
ERROR: Analysis of target '//backend:backend' failed; build aborted: no such package '@javax_servlet_api//jar': java.io.IOException: Error downloading [http://central.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar] to /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/1fc5adba4fa8a524b4199134e1d30997/external/javax_servlet_api/javax.servlet-api-3.1.0.jar: GET returned 501 HTTPS Required
```

Other Bazel CI projects also broke with similar errors. Culprit is, Maven repository no longer supports "http" fetches. Example fix in another repo: bazelbuild/codelabs#30

**Comment by laszlocsomor** [comment]
Thanks to @buachgr, all we need to do is update to using https://github.com/bazelbuild/rules_appengine/commit/339f6aba67fcedb7268cf54d1163cf7704a277ca.

I'll send a PR shortly.

**Comment by c-parsons** [comment]
This is still failing on Ubuntu 18 and Windows:

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1366#bf413424-767e-49e7-9ba7-dc4547a1b6fa

**Comment by c-parsons** [comment]
Also looks perhaps responsible for rules_haskell breakage: 

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1366#eab588bc-bd95-4a43-a143-72dc532943f2

**Comment by laurentlb** [comment]
Any update on this?

(cc @meteorcloudy)

**Comment by meteorcloudy** [comment]
The maven urls has all been updated for CI projects, this can be closed now.
