### ISSUE TITLE
Delete the source-only branch?

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/examples#17]
I have just noticed that this repository contained an unmaintained, source-only branch. Should we delete it?

**Comment by kchodorow** [comment]
Done.

**Comment by msufa** [comment]
That branch was referenced in the [tutorial](https://bazel.io/versions/master/docs/tutorial/environment.html#get-the-sample-project). So we either need to bring it back or update the documentation. I myself needed to spend quite some time to figure out why the tutorial commands are not working, so I believe that others working through it will be similarly confused.

**Comment by kchodorow** [comment]
Arg, I thought it was and I looked at the tutorial, but I didn't see any references to it (and search wasn't working (https://github.com/bazelbuild/bazel/issues/1757).  I'll see if I can restore it from my local repo.

**Comment by kchodorow** [comment]
Added it back.

**Comment by damienmg** [comment]
Can we make a script to maintain that branch?
