### ISSUE TITLE
rules_apple dependency needs to be updated

### ISSUE THREAD

**Issue by mai93** [bazelbuild/examples#207]
[build_bazel_rules_apple was broken](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2045#6580f779-4394-447a-a647-c5b68827ab64) by changes to Bazel at HEAD. The aspect apple_common.objc_proto_aspect was removed from apple_common and accordingly [removed from rule_factory.bzl](https://github.com/bazelbuild/rules_apple/commit/a49fe1b808a42d7eb352d289234bbe2f43e8e1b0#diff-4a7ae7309bfed96760d671ad00e5726a6d0c466112275402d9944abd295d7328) but the commit used for rules_apple still refers to it. We need to update build_bazel_rules_apple to head to fix this.

**Comment by Wyverald** [comment]
I have a PR ready at  https://github.com/bazelbuild/examples/pull/205

**Comment by aiuto** [comment]
Resolved by #205
