### ISSUE TITLE
can place a macro just like the "book"  in other.bzl instead of MODULE.bazel?

### ISSUE THREAD

**Issue by wondfor** [bazelbuild/examples#276]
https://github.com/bazelbuild/examples/blob/b88cad9825e80b73894154c8b73aefe8d5791bd4/bzlmod/05-integrate_third_party_package_manager/MODULE.bazel#L33

can place a macro just like the "book"  in other.bzl instead of MODULE.bazel?

**Comment by Wyverald** [comment]
That wouldn't work. You can't `load` in MODULE.bazel.
