### ISSUE TITLE
third-party-dependencies gtest_test error 

### ISSUE THREAD

**Issue by lyqaiym** [bazelbuild/examples#297]
mac os

this demo the version of gtest is 1.8.1.
cd third-party-dependencies 
bazel build gtest_test
Build completed successfully.

but https://bazel.google.cn/tutorials/cpp-use-cases?hl=zh-cn
the version of gtest is 1.10.0.

external/bazel_tools/platforms/BUILD:89:6: Analysis of target '@bazel_tools//platforms:windows' failed

**Comment by alexeagle** [comment]
Sorry, there's not enough information here to reproduce a bug in this repo. I think you're suggesting that if we upgrade gtest to a newer version, then a build will start failing?
