### ISSUE TITLE
Error: 'JavaInfo' value has no field or method 'transitive_deps'

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/examples#301]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3245#018a06d1-f59f-40fc-aa5c-f33931b33b2f

Platform : Ubuntu, MacOS, Windows

Logs :
```
inputs = depset(jdeps, transitive = [depset([], transitive = [dep.transitive_deps for dep in deps])])
Error: 'JavaInfo' value has no field or method 'transitive_deps'

```
Culprit : https://github.com/bazelbuild/bazel/commit/72058be0628e84741232cb116a7199eb92638f84

CC Greenteam @Wyverald

**Comment by sgowroji** [comment]
@hvadehra Should we update this with [rules_kotlin](https://github.com/bazelbuild/rules_kotlin/commit/20ff6ac82b801acbf28678e0ed325bbce957640e)

**Comment by hvadehra** [comment]
> @hvadehra Should we update this with [rules_kotlin](https://github.com/bazelbuild/rules_kotlin/commit/20ff6ac82b801acbf28678e0ed325bbce957640e)

Yes that SGTM

**Comment by sgowroji** [comment]
Hi @Bencodes, Do you any chance can take a look [https://github.com/bazelbuild/examples/pull/303#issuecomment-1735961456,](https://github.com/bazelbuild/examples/pull/303#issuecomment-1735961456,) As this issue is pending from long time. Thanks!

**Comment by sgowroji** [comment]
Bazel CI is Green now for [examples](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3699). We can close this issue now. Thanks!
