### ISSUE TITLE
Tutorial instructions for building `ios-app.xcodeproj` seem incorrect

### ISSUE THREAD

**Issue by wileykestner** [bazelbuild/examples#42]
The README.md in the tutorial for building an iOS app states:

"Bazel will generate some output files, most notably `bazel-bin/ios-app/ios-app.xcodeproj`"

But when I run `bazel build //ios-app`

It appears that no `ios-app.xcodeproj` is generated in the `bazel-bin` folder.

Running bazel `0.5.4-homebrew`

**Comment by alexeagle** [comment]
I think this is outdated, the ios examples have moved to rules_apple.
