### ISSUE TITLE
Update tutorial for changes to rules_apple

### ISSUE THREAD

**Issue by katre** [bazelbuild/examples#54]
The tutorial is now failing due to changes in Bazel's apple_common. Looks like we just need to update the version of rules_apple being used.

**Comment by katre** [comment]
Can't update this until https://github.com/bazelbuild/rules_apple/issues/127 is resolved.

**Comment by laurentlb** [comment]
Any update?

**Comment by katre** [comment]
Seems to be no motion on https://github.com/bazelbuild/rules_apple/issues/127

**Comment by katre** [comment]
Closing due to inaction.
