### ISSUE TITLE
Add example for cc_library 'toolchains' option to use a different compiler

### ISSUE THREAD

**Issue by startcode** [bazelbuild/examples#68]
Hi, I am working on compiling a c++ and cuda project with bazel. In the project, there is a ".cu" file that I want to compile with nvcc to get a .so library, and everything else will be compiled with g++. The g++ binary code can be linked with the library compiled by nvcc.

I found that there is a[ 'toolchains' option in cc_library ](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.toolchains) I thought I might be able to use the option to let bazel compile the ".cu" file with nvcc. 
I am not sure this is the right way to use the 'toolchains' option, 
but I did not find any example use case of this option. Can anyone provide one 'cc_library' example that uses the 'toolchains' option? 

Thanks.

**Comment by mhlopko** [comment]
I don't think this does what it looks like it does :)

**Comment by katre** [comment]
Closing this as obsolete.

**Comment by luxe** [comment]
I'm still unsure how "toolchains" are supposed to be used.  Does it affect the toolchain evaluation for an individual rule?  do they correlate to the `cc_toolchain_config`, `cc_toolchain`, etc?  Because trying to use a toolchain created this way results in: 
```
does not have mandatory providers: 'TemplateVariableInfo'
```
and I'm not sure if I'm mixing concept here.

**Comment by katre** [comment]
The existing `toolchains` attribute can only be used to provide templated Make-style variables to rules that use them: it is very restricted. We will at some point either remove it or make it work properly with actual toolchains, but this is not a current priority.
