### ISSUE TITLE
 bazel build //main:hello-world failed

### ISSUE THREAD

**Issue by ryankumar** [bazelbuild/examples#89]
when i run  bazel build //main:hello-world it gives an error like this

No command 'bazel' found, did you mean:
 Command 'babel' from package 'babel-1.4.0' (universe)
 Command 'babel' from package 'openbabel' (universe)
bazel: command not found

**Comment by laurentlb** [comment]
Hi,

Please install `bazel` first: https://docs.bazel.build/versions/master/install.html
If you've installed it, you may need to update the PATH variable.
